server:
    port: 8080
logging:
    level:
        org:
            hibernate:
                SQL: debug
management:
    address: 127.0.0.1
    context-path: /manage
    port: 9001
    security:
        enabled: false
        roles: ACTUATOR,ADMIN
    endpoints:
        web:
            cors:
                allowed-origins=: http://localhost:4200,http://localhost:8080
                allowed-methods: POST, GET, PUT, OPTIONS, DELETE
security:
    basic:
        enabled: false
    user:
        name: act
        password: act
spring:
    datasource:
        name: testData
    h2:
        console:
            enabled: true
    jmx:
        default-domain: jpa.sample
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
            naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    liquibase:
        change-log: classpath:/db/changelog/db.changelog-master.xml
        enabled: true
        password: ''
        url: jdbc:h2:mem:testData
        user: sa
keycloak:
    auth-server-url: http://localhost:8180/auth
    realm: api
    resource: app
    public-client: true
    principal-attribute: preferred_username